services:
  attachment-expiry-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ipcom-attachment-expiry
    environment:
      - DOTNET_ENVIRONMENT=Production
    
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    # Use network_mode host to connect to localhost services
    network_mode: host